---
title: "Ⅳ. 컴퓨팅 사고 Ⅳ"
author: "ne_choi"
date: '2021 01 09 '
output:
  html_document:
   toc: true
   toc_float:
     collapsed: false
     smooth_scroll: true
   theme: united
   highlight: textmate
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* POSTECH에서 제공하는 [MOOC](https://pabi.smartlearn.io/) 중, 컴퓨팅 사고 Ⅰ 과정입니다. 

# Ⅳ. 컴퓨팅 사고 Ⅳ
## 1. 계산 자료
### 기본 자료: 더 이상 쪼갤 수 없는 자료
- 성적 총합은 1729이다
- 생활기록부가 아직 남아 있다
- 생활기록부가 이제 남아 있지 않다
- 가장 가까운 도시는 부산이다
- 시험이 끝나는 날은 수요일이다

### Python 언어의 기본 자료
- 정수
- 논리값: True / False
- 문자열: '안녕하세요?', '', "안녕", ' ', '"ㅇㅇ"', "'ㄷㄷ'"

### 문자열 해석하기
- 문자열이 표현하는 단어와 문장을 프로그램으로 해석하지 않음
  - '1729': 글자로 이루어진 단어, 정수 1729와 무관

### 기본 자료 = 프로그램 = 계산 결과


## 2. 여러곱- 계산 자료의 '그리고'
### 접속사 '그리고'
- 계산 자료 종류
  - 생활기록부에서 이름 **그리고** 성적을 뽑아낸다.
  - 지도에서 출발 도시 **그리고** 도착 도시를 골라서 거리를 잰다.
- 계산 자료 자체
  - 첫째 생활기록부에는 이름 홍길동 **그리고** 성적 85점이 적혀 있다.
  - 국어 **그리고** 영어 **그리고** 수학은 공통 수강생이 있다.

### Python 언어 여러곱
- 괄호 사이 계산 자료를 나열하고 쉼표로 분리
- 각 계산 자료 = 여러곱 원소(계산 자료 1, 계산 자료 2, ..., 계산 자료 n)

### 여러곱의 특수한 형태
- 계산 자료 하나로 엮은 여러곱
- 원소가 없는 여러곱

### 여러곱의 특징
- 여러곱 = 프로그램
- 더 큰 여러곱을 만들 때 쓸 수 있음
  - ((1729, 'Hello'), True)

## 3. 여러합- 계산 자료의 '또는'
### 접속사 '또는'
- 계산 자료 종류
  - 생활기록부를 찾으려면 이름 **또는** 생년월일이 필요하다.
- 계산 자료 자체
  - 시험은 월요일 **또는** 화요일 **또는** 수요일에 시작한다.

### 여러합
- 접속사 **또는**을 써서 정의한 합집합
- 개별 원소는 종류와 내용을 포함

### Python 언어 여러합
- 종류와 내용 쌍으로 이뤄진 여러곱으로 여러합 원소를 표현
- 내용이 없으면 종류만으로 이루어진 여러곱으로 표현

