---
title: "Ⅰ. 컴퓨팅 사고 Ⅰ"
author: "ne_choi"
date: '2021 01 08 '
output:
  html_document:
   toc: true
   toc_float:
     collapsed: false
     smooth_scroll: true
   theme: united
   highlight: textmate
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* POSTECH에서 제공하는 [MOOC](https://pabi.smartlearn.io/) 중, 컴퓨팅 사고 Ⅰ 과정입니다.    

# Ⅰ. 컴퓨팅 사고 Ⅰ
## 1. 계산으로 풀 수 있는 문제
### 계산으로 푸는 문제
- 생각하는 과정이 필요
- 어떤 형태로든 암산을 거쳐야 함
- 난이도에 따라 종이에 중간 결과를 적어야 함


## 2. 생활기록부 성적 평균 구하기
### 생활기록부 성적 평균 구하기
- 계산 과정
  1. 성적을 모두 더한다.  
  2. 학생 수를 구한다.  
  3. 성적 총합을 학생 수로 나눈다.  

- 필요한 가정
  - 성적을 모두 더할 수 있다.  
  - 학생 수를 구할 수 있다.  

### 계산 과정을 이해 못할 때,
1. 성적을 모두 더한다.  
   1-1. 성적 총합으로 종이에 0을 쓴다.  
   1-2. 생활기록부를 순서대로 헤아려서 개별 성적을 총합에 더해 덮어쓴다.  
   1-3. 종이에 적힌 최종 값을 읽는다.  

2. 학생 수를 구한다.  
   2-1. 학생 수로 종이에 0을 쓴다.  
   2-2. 다시 생활기록부를 순서대로 헤어려서 학생 수에 1을 더해 덮어쓴다.  
   2-3. 종이에 적힌 최종 값을 읽는다.  

3. 성적 총합을 학생 수로 나눈다.  

### 생활기록부를 순서대로 헤어린다를 이해 못할 때,
1-2. 생활기록부를 순서대로 헤아리며 개별 성적을 총합에 더해 덮어준다.  
   1-2-1. 더미 맨 위에 놓인 생활기록부를 가져온다.  
   1-2-2. 생활기록부에 적힌 성적을 현재 총합에 더해 기억한다.  
   1-2-3. 종이에 새로운 성적 총합을 덮어 쓴다.  
   1-2-4. 생활기록부가 남아 있으면 1-2-1로 돌아간다.  

2-2. 다시 생활기록부를 순서대로 헤아리며 학생 수에 1 더해서 덮어쓴다.  
   2-2-1. 더미 맨 위에 놓인 생활기록부를 가져온다.  
   2-2-2. 현재 학생 수에 1을 더해 기억한다.  
   2-2-3. 종이에 새로운 학생 수를 덮어 쓴다.  
   2-2-4. 생활기록부가 남아 있으면 2-2-1로 돌아간다.  


## 3. 계산의 네 가지 요소
### 계산의 요소
- 계산 대상 → 계산
- 계산 언어, 계산 과정, 계산 수행이 모두 들어감

### 계산 수행 주체
- 계산 과정은 계산 수행 주체가 이해하는 언어로 작성해야 함

### 계산 설계
- 계산으로 문제 풀 때 핵심
- 계산으로 답을 구하기까지의 시간 결정
- 설계가 엉망이면?
  - 계산 수행 주체의 능력이 뛰어나도 시간이 많이 소요됨
- 설계를 잘하면?
  - 계산 수행 주체의 능력이 크게 영향을 미치지 않음  


## 4. 계산 설계하기
### 계산 = 무엇 + 어떻게
- 무엇: 계산 대상
- 어떻게: 계산 과정

### 생활기록부 성적 평균 구하기
- 계산 대상: 성적(계산 자료)
  - 범위: 문제 시작, 중간 계산 결과, 문제의 답
  
- 계산 자료: 계산 대상이 같아도 문제에 따라 달라짐

- 계산 과정: 연산과 명력의 조합
  - 연산: 외부와 소통하지 않고 수행, 외부에 영향을 미치지 않음
  - 명령: 외부와 소통, 외부에 영향을 미침

- 연산을 명령으로부터 구분하는 이유
  - 연산은 다시 수행해도 결과가 같음(전체 설계가 덜 복잡함)
  - 명령은 수행할 때마다 결과가 달라짐(전체 설계가 복잡해짐)
