---
title: "Ⅴ. 컴퓨팅 사고 Ⅴ" 
author: "ne_choi"
date: '2021 01 13 '
output:
  html_document:
   toc: true
   toc_float:
     collapsed: false
     smooth_scroll: true
   theme: united
   highlight: textmate
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* POSTECH에서 제공하는 [MOOC](https://pabi.smartlearn.io/) 중, 컴퓨팅 사고 Ⅱ 과정입니다. 

# Ⅴ. 컴퓨팅 사고 Ⅴ
## 1. 순서열- 계산 자료의 '더미'
### 계산 자료 = 같은 꼴의 더미
- 같은 꼴의 더미로 만들어주어 컴퓨터가 계산하게 함

### 순서열
- 같은 꼴의 더미를 표현
  - [계산자료1, 계싼자료2, ..., 계산자료n]
- 예
  - []
  - [1]
  - [1,2,2,3,3,3]
  - ['월요일', '화요일', '수요일']

### 다음 유도하기로 더미 해석하기
- 최초 빈 더미
  - []
- 직전 더미에 원소 하나 추가
  - [1,2,3] + [100] = [100,1,2,3] (맨 앞에 덧붙여짐)

### 다음 유도하기에 맞춰 순서열 만들기
- 해당 기능을 바로 쓸 수 없고, 다른 기능을 이용해 표현
- 빈 순서열
  - []
- 작은 순서열 맨 앞에 원소 하나를 덧붙여 얻은 순서열
  - [원소] + 작은 순서열
    - [1] == [1] + []
    - [2,3] == [2] + [3]
    - [1,2,3] == [1] + [2,3]

### 순서열과 여러곱
- 여러곱
  - 원소 개수가 고정
  - 원소를 추가하면 새로운 꼴의 여러곱이 나옴
    - 서울 그리고 대전
    - 서울 그리고 대전 그리고 부산
- 순서열
  - 원소가 몇 개 포함될지 미정
  - 원소를 추가해도 종류가 달라지지 않음
    - 서울, 대전 더미
    - 서울, 대전, 부산 더미

### Python 언어에서 여러합 원소 더미
- pythoh에서 여러합을 바로 나타낼 수 없음
- 예: 이름 또는 생년월일 더미
  - 이름 홍길동, 생년월일 1981년 9월 18일 더미
  - [('이름','홍길동'),('생년월일',(1981,9,18))]
  - 같은 꼴의 더미를 표현하는 순서열도 실제 원소 꼴은 다를 수 있음

### 순서열을 쓸 수 있는 곳
- 기본 자료가 나올 수 있는 곳 전부
  - 예: 여러곱 원소, 순서열 원소

### 해석
- 원소 두 개 여러곱 = 대응 관계
  - 대응 관계 해석
    - (계산자료1, 계산자료2) ⇔ 계산자료1은 계산자료2에 대응된다,
    - ('인천', 40) ⇔ 인천은 40km에 대응된다. / 인천 특징은 40km이다.
    - ('서울', [('인천',40),('대전',163),('강릉',237)])
    - ⇔ 서울 특징으로 인천은 40km에 대응되고 대전은 163km에 대응되고 강릉은 237km에 대응된다.

### 정리
- 계산 자료
  - 기본 자료: 정수, 논리값, 문자열
  - 여러곱: - 그리고 -, -에 대응된다
  - 여러합: - 또는 -
  - 순서열: - 더미


## 2. 다음 유도하기로 계산 자료 만들기
### 다음 유도하기와 여러합
- 다음 유도하기에서 계산 자료
  - '최초 경우' 또는(여러합) '작은 것으로부터 더 큰 것을 이끌어 내는 경우'
    - 여러합 원소 = (종류, 내용)
    - Python 언어에서 만들어 낼 수 있음

### 계산 자료 조합하기
- 기본 자료: 정수, 논리값, 문자열
- 여러곱: - 그리고 -, -에 대응된다
- 여러합: - 또는 -
- 순서열: - 더미
- + 다음 유도하기로 정의하기